export const GET_CHATS = "GET_CHATS";
export const GET_CHATS_SUCCESS = "GET_CHATS_SUCCESS";
export const GET_CHATS_FAILURE = "GET_CHATS_FAILURE";

export const GET_CHAT = "GET_CHAT";
export const GET_CHAT_SUCCESS = "GET_CHAT_SUCCESS";
export const GET_CHAT_FAILURE = "GET_CHAT_FAILURE";

export const CREATE_CHAT = "CREATE_CHAT";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_FAILURE = "CREATE_CHAT_FAILURE";

export const UPDATE_CHAT = "UPDATE_CHAT";
export const UPDATE_CHAT_SUCCESS = "UPDATE_CHAT_SUCCESS";
export const UPDATE_CHAT_FAILURE = "UPDATE_CHAT_FAILURE";

export const DELETE_CHAT = "DELETE_CHAT";
export const DELETE_CHAT_SUCCESS = "DELETE_CHAT_SUCCESS";
export const DELETE_CHAT_FAILURE = "DELETE_CHAT_FAILURE";

export const GET_CHAT_MESSAGES = "GET_CHAT_MESSAGES";
export const GET_CHAT_MESSAGES_SUCCESS = "GET_CHAT_MESSAGES_SUCCESS";
export const GET_CHAT_MESSAGES_FAILURE = "GET_CHAT_MESSAGES_FAILURE";

export const GET_CHAT_MESSAGE = "GET_CHAT_MESSAGE";
export const GET_CHAT_MESSAGE_SUCCESS = "GET_CHAT_MESSAGE_SUCCESS";
export const GET_CHAT_MESSAGE_FAILURE = "GET_CHAT_MESSAGE_FAILURE";

export const CREATE_CHAT_MESSAGE = "CREATE_CHAT_MESSAGE";
export const CREATE_CHAT_MESSAGE_SUCCESS = "CREATE_CHAT_MESSAGE_SUCCESS";
export const CREATE_CHAT_MESSAGE_FAILURE = "CREATE_CHAT_MESSAGE_FAILURE";

export const UPDATE_CHAT_MESSAGE = "UPDATE_CHAT_MESSAGE";
export const UPDATE_CHAT_MESSAGE_SUCCESS = "UPDATE_CHAT_MESSAGE_SUCCESS";
export const UPDATE_CHAT_MESSAGE_FAILURE = "UPDATE_CHAT_MESSAGE_FAILURE";

export const DELETE_CHAT_MESSAGE = "DELETE_CHAT_MESSAGE";
export const DELETE_CHAT_MESSAGE_SUCCESS = "DELETE_CHAT_MESSAGE_SUCCESS";
export const DELETE_CHAT_MESSAGE_FAILURE = "DELETE_CHAT_MESSAGE_FAILURE";
