import { images } from "../assets"
import { AppHelper } from "../helper"

const planners = [
  {
    name: 'Haroon Tahir',
    id: 'planner1',
    description: 'Planner 1 description',
    categories: ['Wedding', 'Birthday', 'Party'],
    image: images.Users.Profile,
    earned: 1000,
    status: 'Online',
    statusColor: AppHelper.material.green500,
    price: 100,
    currency: 'USD',
    rating: 4.5,
    reviews: 100,
    duration: 5,
    durationType: 'days',
    location: 'New York',
    locationType: 'city',
    tags: ['tag1', 'tag2', 'tag3'],
    isPopular: true,
    isFeatured: true,
    isExclusive: true,
    isBestSeller: true,
    isTrending: true,
    isTopRated: true,
    isTopSeller: true,
    isTopDestination: true,
    isTopLocation: true,
    isTopPick: true,
    isTopChoice: true,
  },
  {
    name: 'Mohammad Nawal Ali',
    id: 'planner2',
    description: 'Planner 2 description',
    categories: ['Wedding', 'Birthday', 'Party'],
    image: images.Users.Profile,
    price: 200,
    status: 'Offline',
    statusColor: AppHelper.material.red500,
    currency: 'USD',
    rating: 4.5,
    reviews: 100,
    duration: 5,
    durationType: 'days',
    location: 'New York',
    locationType: 'city',
    tags: ['tag1', 'tag2', 'tag3'],
    isPopular: true,
    isFeatured: true,
    isExclusive: true,
    isBestSeller: true,
    isTrending: true,
    isTopRated: true,
    isTopSeller: true,
    isTopDestination: true,
    isTopLocation: true,
    isTopPick: true,
    isTopChoice: true,
  },
  {
    name: 'Abdur Rehman',
    id: 'planner3',
    description: 'Planner 3 description',
    categories: ['Wedding', 'Birthday', 'Party'],
    image: images.Users.Profile,
    status: 'Away',
    statusColor: AppHelper.material.yellow500,
    price: 300,
    currency: 'USD',
    rating: 4.5,
    reviews: 100,
    duration: 5,
    durationType: 'days',
    location: 'New York',
    locationType: 'city',
    tags: ['tag1', 'tag2', 'tag3'],
    isPopular: true,
    isFeatured: true,
    isExclusive: true,
    isBestSeller: true,
    isTrending: true,
    isTopRated: true,
    isTopSeller: true,
    isTopDestination: true,
    isTopLocation: true,
    isTopPick: true,
    isTopChoice: true,
  },
  {
    name: 'Asad Kamran',
    id: 'planner4',
    description: 'Planner 4 description',
    categories: ['Wedding', 'Birthday', 'Party'],
    status: 'Do not Disturb',
    statusColor: AppHelper.material.purple500,
    image: images.Users.Profile,
    price: 400,
    currency: 'USD',
    rating: 4.5,
    reviews: 100,
    duration: 5,
    durationType: 'days',
    location: 'New York',
    locationType: 'city',
    tags: ['tag1', 'tag2', 'tag3'],
    isPopular: true,
    isFeatured: true,
    isExclusive: true,
    isBestSeller: true,
    isTrending: true,
    isTopRated: true,
    isTopSeller: true,
    isTopDestination: true,
    isTopLocation: true,
    isTopPick: true,
    isTopChoice: true,
  },
]

const packages = [
  {
    name: 'Package 1',
    id: 'package1',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    categories: ['Wedding', 'Birthday', 'Party'],
    image: images.PartyPlanner,
    price: 15000,
    currency: 'PKR',
    rating: 4.5,
    reviews: 100,
  },
  {
    name: 'Package 2',
    id: 'package2',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    categories: ['Wedding', 'Birthday', 'Party'],
    image: images.WeddingPlanner,
    price: 15000,
    currency: 'PKR',
    rating: 4.5,
    reviews: 100,
  },
  {
    name: 'Package 3',
    id: 'package3',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    categories: ['Wedding', 'Birthday', 'Party'],
    image: images.WeeklyPlanner,
    price: 15000,
    currency: 'PKR',
    rating: 4.5,
    reviews: 100,
  },
  {
    name: 'Package 4',
    id: 'package4',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    categories: ['Wedding', 'Birthday', 'Party'],
    image: images.WorkPlanner,
    price: 15000,
    currency: 'PKR',
    rating: 4.5,
    reviews: 100,
  },
];

export { planners, packages };