export const ScreenNavigator = {
  Login: "Login",
  Signup: "Signup",
  Phases: "Phases",
  Planner: "Planner",
  Client: "Client",
  Chat: "Chat",
  ForgotPassword: "ForgotPassword",
  PlannerHome: "PlannerHome",
  PlannerSearch: "PlannerSearch",
  PlannerJob: "PlannerJob",
  PlannerMessage: "PlannerMessage",
  PlannerNotifications: "PlannerNotifications",
  ClientHome: "ClientHome",
  ClientSearch: "ClientSearch",
  ClientJob: "ClientJob",
  ClientMessage: "ClientMessage",
  ClientNotifications: "ClientNotifications",
  PlannerProfile: "PlannerProfile",
  ClientProfile: "ClientProfile",
  JobDetail: "JobDetail",
  Packages: "Packages"
}