export const ScreenNavigator = {
  Login: "Login",
  Signup: "Signup",
  Phases: "Phases",
  Planner: "Planner",
  Client: "Client",
  Chat: "Chat",
  ForgotPassword: "ForgotPassword",

  PlannerHome: "PlannerHome",
  PlannerSearch: "PlannerSearch",
  PlannerJob: "PlannerJob",
  PlannerMessage: "PlannerMessage",
  PlannerNotifications: "PlannerNotifications",
  PlannerProfile: "PlannerProfile",
  PlannerProfileForClient: "PlannerProfileForClient",
  PlannerAnalytics: "PlannerAnalytics",
  PlannerPackages: "PlannerPackages",
  PlannerGetFeatured: "PlannerGetFeatured",
  
  ClientHome: "ClientHome",
  ClientSearch: "ClientSearch",
  ClientJob: "ClientJob",
  ClientMessage: "ClientMessage",
  ClientNotifications: "ClientNotifications",
  ClientProfile: "ClientProfile",
  ClientAnalytics: "ClientAnalytics",
  ClientJobPosting: "ClientJobPosting",
  ClientProposals: "ClientProposals",
  
  JobDetail: "JobDetail",
  
  Packages: "Packages",
  PackageDetail: "PackageDetail",
  
  EditProfile: "EditProfile",
  SavedPlanner: "SavedPlanner",

  TaskManagementHome: "TaskManagementHome",
  TaskManagementTask: "TaskManagementTask",
  TaskManagementTaskDetail: "TaskManagementTaskDetail",
  TaskManagementTaskDetailEdit: "TaskManagementTaskDetailEdit",
  TaskManagementTaskDetailAdd: "TaskManagementTaskDetailAdd",
  TaskManagementTaskDetailAddSubTask: "TaskManagementTaskDetailAddSubTask",
  TaskManagementTaskDetailAddSubTaskEdit: "TaskManagementTaskDetailAddSubTaskEdit",
  PostTestimonials: "PostTestimonials",
}